import type { Creation } from "./types";

const HEX = "0123456789abcdef";

function randomHex(length: number) {
  let out = "";
  for (let i = 0; i < length; i++) {
    out += HEX[Math.floor(Math.random() * HEX.length)];
  }
  return out;
}

export const randomAddress = () => `0x${randomHex(40)}`;

export const randomTxHash = () => `0x${randomHex(64)}`;

export const newId = (prefix: string) => `${prefix}-${randomHex(6)}`;

export const MOCK_ADDRESS = "0x3fa4bD1C97e56A0f8B2c41d90Ee77A5b19cC0de1";

const DAY_MS = 24 * 60 * 60 * 1000;
const BASE_MS = 1_700_000_000_000;
const daysAgo = (days: number) => BASE_MS - days * DAY_MS;

const FIXED_TX = "0x9f2c4a7e1b8d3f6a5c0e9d2b7a4f1e8c3d6b9a2f5e8c1b4d7a0f3e6c9b2d5a8";
const FIXED_CONTRACT = "0x5e8c1b4d7a0f3e6c9b2d5a8f1e4c7b0d3a6f9e2c5b8d1a4f7c0e3b6d9a2f5c8";

function seedTx(seed: string) {
  return `${FIXED_TX.slice(0, 66 - seed.length)}${seed}`;
}

function seedContract(seed: string) {
  return `0x${seed}${FIXED_CONTRACT.slice(2 + seed.length)}`;
}

export const SEED_CREATIONS: Creation[] = [
  {
    kind: "token",
    standard: "erc20",
    id: "tok-forgecoin",
    name: "ForgeCoin",
    symbol: "FORGE",
    decimals: 18,
    initialSupply: "1000000",
    priceUsd: "0.42",
    description: "Community currency of the ForgePlace ecosystem.",
    chain: "ethereum",
    createdAt: daysAgo(12),
    txHash: seedTx("01"),
    contractAddress: seedContract("aa11"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-anvil",
    name: "Anvil Token",
    symbol: "ANVL",
    decimals: 18,
    initialSupply: "250000000",
    priceUsd: "0.07",
    description: "Rewards token for builders and early adopters.",
    chain: "polygon",
    createdAt: daysAgo(5),
    txHash: seedTx("02"),
    contractAddress: seedContract("bb22"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-novacredit",
    name: "Nova Credit",
    symbol: "NOVA",
    decimals: 6,
    initialSupply: "50000000",
    priceUsd: "1.25",
    description: "Stable-ish credits for the Base ecosystem.",
    chain: "base",
    createdAt: daysAgo(3),
    txHash: seedTx("03"),
    contractAddress: seedContract("cc33"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-feldspar",
    name: "Feldspar",
    symbol: "FLDR",
    decimals: 18,
    initialSupply: "900000000",
    priceUsd: "0.03",
    chain: "arbitrum",
    createdAt: daysAgo(1),
    txHash: seedTx("04"),
    contractAddress: seedContract("dd44"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-gilded",
    name: "Gilded",
    symbol: "GLD",
    decimals: 18,
    initialSupply: "120000000",
    priceUsd: "0.052",
    chain: "optimism",
    createdAt: daysAgo(16),
    txHash: seedTx("16"),
    contractAddress: seedContract("a1c2"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-terminal",
    name: "Project Terminal",
    symbol: "TERM",
    decimals: 18,
    initialSupply: "420000000",
    priceUsd: "0.88",
    chain: "base",
    createdAt: daysAgo(14),
    txHash: seedTx("17"),
    contractAddress: seedContract("b3d4"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-quartz",
    name: "Quartz",
    symbol: "QRTZ",
    decimals: 6,
    initialSupply: "30000000",
    priceUsd: "2.4",
    chain: "polygon",
    createdAt: daysAgo(13),
    txHash: seedTx("18"),
    contractAddress: seedContract("c5e6"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-pulse",
    name: "Pulse",
    symbol: "PLSE",
    decimals: 18,
    initialSupply: "750000000",
    priceUsd: "0.013",
    chain: "ethereum",
    createdAt: daysAgo(11),
    txHash: seedTx("19"),
    contractAddress: seedContract("d7f8"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-ember",
    name: "Ember",
    symbol: "EMBR",
    decimals: 18,
    initialSupply: "85000000",
    priceUsd: "0.19",
    chain: "arbitrum",
    createdAt: daysAgo(10),
    txHash: seedTx("1a"),
    contractAddress: seedContract("e9a0"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-vector",
    name: "Vector",
    symbol: "VCTR",
    decimals: 9,
    initialSupply: "15000000",
    priceUsd: "3.6",
    chain: "optimism",
    createdAt: daysAgo(9),
    txHash: seedTx("1b"),
    contractAddress: seedContract("f0b1"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-cyan",
    name: "Cyan",
    symbol: "CYAN",
    decimals: 18,
    initialSupply: "600000000",
    priceUsd: "0.0042",
    chain: "base",
    createdAt: daysAgo(8),
    txHash: seedTx("1c"),
    contractAddress: seedContract("a2c3"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-rift",
    name: "Rift",
    symbol: "RIFT",
    decimals: 18,
    initialSupply: "200000000",
    priceUsd: "0.71",
    chain: "polygon",
    createdAt: daysAgo(7),
    txHash: seedTx("1d"),
    contractAddress: seedContract("b4d5"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-halo",
    name: "Halo",
    symbol: "HALO",
    decimals: 18,
    initialSupply: "900000000",
    priceUsd: "0.035",
    chain: "ethereum",
    createdAt: daysAgo(6),
    txHash: seedTx("1e"),
    contractAddress: seedContract("c6e7"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-molar",
    name: "Molar",
    symbol: "MOLR",
    decimals: 6,
    initialSupply: "25000000",
    priceUsd: "1.9",
    chain: "arbitrum",
    createdAt: daysAgo(4),
    txHash: seedTx("1f"),
    contractAddress: seedContract("d8f9"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-prisma",
    name: "Prisma",
    symbol: "PRSM",
    decimals: 18,
    initialSupply: "130000000",
    priceUsd: "0.26",
    chain: "base",
    createdAt: daysAgo(2),
    txHash: seedTx("20"),
    contractAddress: seedContract("e0a1"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "token",
    standard: "erc20",
    id: "tok-demember",
    name: "Dark Ember",
    symbol: "DEMB",
    decimals: 18,
    initialSupply: "70000000",
    priceUsd: "5.2",
    chain: "optimism",
    createdAt: daysAgo(0),
    txHash: seedTx("21"),
    contractAddress: seedContract("f2b3"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "collection",
    standard: "erc721",
    id: "col-pioneers",
    name: "Forge Pioneers",
    symbol: "PION",
    description: "One-of-one founders pass with onchain traits.",
    volumeEth: "14.52",
    floorPriceEth: "0.85",
    chain: "ethereum",
    createdAt: daysAgo(9),
    txHash: seedTx("05"),
    contractAddress: seedContract("ee55"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "collection",
    standard: "erc1155",
    id: "col-gemfragments",
    name: "Gem Fragments",
    symbol: "GEMF",
    description: "Multi-edition gem shards for in-game crafting.",
    volumeEth: "6.10",
    floorPriceEth: "0.12",
    chain: "base",
    createdAt: daysAgo(4),
    txHash: seedTx("06"),
    contractAddress: seedContract("ff66"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "collection",
    standard: "erc721",
    id: "col-neonrunners",
    name: "Neon Runners",
    symbol: "NRUN",
    description: "Generative neon avatars racing across Polygon.",
    volumeEth: "8.35",
    floorPriceEth: "0.40",
    chain: "polygon",
    createdAt: daysAgo(7),
    txHash: seedTx("07"),
    contractAddress: seedContract("ab12"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "collection",
    standard: "erc1155",
    id: "col-deepsky",
    name: "Deep Sky",
    symbol: "DKSKY",
    description: "Vast astrophotography prints in limited editions.",
    volumeEth: "2.20",
    floorPriceEth: "0.05",
    chain: "arbitrum",
    createdAt: daysAgo(2),
    txHash: seedTx("08"),
    contractAddress: seedContract("cd34"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "collection",
    standard: "erc721",
    id: "col-rhythmproto",
    name: "Rhythm Protocol",
    symbol: "RHYM",
    description: "One-of-one music NFT passes for live drops.",
    volumeEth: "1.20",
    floorPriceEth: "0.10",
    chain: "optimism",
    createdAt: daysAgo(6),
    txHash: seedTx("09"),
    contractAddress: seedContract("ef56"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc721",
    id: "itm-pion-214",
    name: "Forge Pioneers #214",
    collectionId: "col-pioneers",
    tokenId: 214,
    traits: [
      { traitType: "Background", value: "Ember" },
      { traitType: "Armor", value: "Titanium" },
    ],
    supply: 1,
    mintPriceEth: "0.85",
    buyPriceEth: "0.85",
    listingStatus: "buy",
    category: "Collectibles",
    description: "Founder pass with titanium armor plating.",
    chain: "ethereum",
    createdAt: daysAgo(9),
    txHash: seedTx("0a"),
    contractAddress: seedContract("a7b8"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc721",
    id: "itm-pion-215",
    name: "Forge Pioneers #215",
    collectionId: "col-pioneers",
    tokenId: 215,
    traits: [
      { traitType: "Background", value: "Glacier" },
      { traitType: "Armor", value: "Obsidian" },
    ],
    supply: 1,
    mintPriceEth: "0.85",
    auctionBaseEth: "0.50",
    highestBidEth: "1.20",
    listingStatus: "auction",
    category: "Collectibles",
    description: "Founder pass with obsidian finish.",
    chain: "ethereum",
    createdAt: daysAgo(8),
    txHash: seedTx("0b"),
    contractAddress: seedContract("c9d0"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc721",
    id: "itm-pion-216",
    name: "Forge Pioneers #216",
    collectionId: "col-pioneers",
    tokenId: 216,
    traits: [
      { traitType: "Background", value: "Aurora" },
      { traitType: "Armor", value: "Bronze" },
    ],
    supply: 1,
    mintPriceEth: "0.85",
    listingStatus: "new",
    category: "Collectibles",
    description: "Freshly minted founders pass.",
    chain: "ethereum",
    createdAt: daysAgo(7),
    txHash: seedTx("0c"),
    contractAddress: seedContract("e1f2"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc721",
    id: "itm-neon-007",
    name: "Neon Runner #007",
    collectionId: "col-neonrunners",
    tokenId: 7,
    traits: [{ traitType: "Glow", value: "Cyan" }],
    supply: 1,
    mintPriceEth: "0.40",
    buyPriceEth: "0.40",
    listingStatus: "buy",
    category: "Art",
    description: "Cyan-glow avatars from the first racing set.",
    chain: "polygon",
    createdAt: daysAgo(7),
    txHash: seedTx("0d"),
    contractAddress: seedContract("a3b4"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc721",
    id: "itm-neon-101",
    name: "Neon Runner #101",
    collectionId: "col-neonrunners",
    tokenId: 101,
    traits: [{ traitType: "Glow", value: "Magenta" }],
    supply: 1,
    mintPriceEth: "0.40",
    auctionBaseEth: "0.25",
    highestBidEth: "0.55",
    listingStatus: "auction",
    category: "Art",
    description: "Rare magenta runner, bidding now.",
    chain: "polygon",
    createdAt: daysAgo(6),
    txHash: seedTx("0e"),
    contractAddress: seedContract("c5d6"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc721",
    id: "itm-rhythm-05",
    name: "Rhythm Protocol #5",
    collectionId: "col-rhythmproto",
    tokenId: 5,
    traits: [{ traitType: "Genre", value: "Electronic" }],
    supply: 1,
    mintPriceEth: "0.10",
    listingStatus: "mintable",
    category: "Music",
    description: "Access pass to the next live drop.",
    chain: "optimism",
    createdAt: daysAgo(6),
    txHash: seedTx("0f"),
    contractAddress: seedContract("e7f8"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc1155",
    id: "itm-gem-ruby",
    name: "Ruby Shard",
    collectionId: "col-gemfragments",
    tokenId: 1,
    traits: [{ traitType: "Cut", value: "Brilliant" }],
    supply: 500,
    mintPriceEth: "0.12",
    listingStatus: "mintable",
    category: "Gaming",
    description: "Crafting shard with brilliant cut.",
    chain: "base",
    createdAt: daysAgo(4),
    txHash: seedTx("10"),
    contractAddress: seedContract("a9b0"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc1155",
    id: "itm-gem-sapphire",
    name: "Sapphire Slab",
    collectionId: "col-gemfragments",
    tokenId: 2,
    traits: [{ traitType: "Cut", value: "Step" }],
    supply: 250,
    mintPriceEth: "0.12",
    buyPriceEth: "0.18",
    listingStatus: "buy",
    category: "Gaming",
    description: "Rare step-cut sapphire slab.",
    chain: "base",
    createdAt: daysAgo(3),
    txHash: seedTx("11"),
    contractAddress: seedContract("c1d2"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc1155",
    id: "itm-gem-emerald",
    name: "Emerald Cluster",
    collectionId: "col-gemfragments",
    tokenId: 3,
    traits: [{ traitType: "Cut", value: "Cabochon" }],
    supply: 150,
    mintPriceEth: "0.12",
    lastSoldEth: "0.21",
    listingStatus: "sold",
    category: "Gaming",
    description: "Group bid shard for the raid season.",
    chain: "base",
    createdAt: daysAgo(2),
    txHash: seedTx("12"),
    contractAddress: seedContract("e3f4"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc1155",
    id: "itm-sky-nebula",
    name: "Deep Sky Nebula",
    collectionId: "col-deepsky",
    tokenId: 1,
    traits: [{ traitType: "Subject", value: "Nebula" }],
    supply: 1000,
    mintPriceEth: "0.05",
    buyPriceEth: "0.05",
    listingStatus: "buy",
    category: "Photography",
    description: "Edition print of the Virgo cluster.",
    chain: "arbitrum",
    createdAt: daysAgo(2),
    txHash: seedTx("13"),
    contractAddress: seedContract("a5b6"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc1155",
    id: "itm-sky-aurora",
    name: "Deep Sky Aurora",
    collectionId: "col-deepsky",
    tokenId: 2,
    traits: [{ traitType: "Subject", value: "Aurora" }],
    supply: 750,
    mintPriceEth: "0.05",
    listingStatus: "new",
    category: "Photography",
    description: "Green sheets over the poles.",
    chain: "arbitrum",
    createdAt: daysAgo(1),
    txHash: seedTx("14"),
    contractAddress: seedContract("c7d8"),
    creatorAddress: MOCK_ADDRESS,
  },
  {
    kind: "item",
    standard: "erc1155",
    id: "itm-sky-comet",
    name: "Deep Sky Comet",
    collectionId: "col-deepsky",
    tokenId: 3,
    traits: [{ traitType: "Subject", value: "Comet" }],
    supply: 300,
    mintPriceEth: "0.05",
    auctionBaseEth: "0.04",
    highestBidEth: "0.09",
    listingStatus: "auction",
    category: "Photography",
    description: "Comet pass, bids end Sunday.",
    chain: "arbitrum",
    createdAt: daysAgo(1),
    txHash: seedTx("15"),
    contractAddress: seedContract("e9f0"),
    creatorAddress: MOCK_ADDRESS,
  },
];
